export class PlayerUpdateType {
  static INSTRUMENT = 0
  static NOTE = 1
  static PROBABILITY = 2
  static MIN_VELOCITY = 3
  static MAX_VELOCITY = 4
  static MUTE = 5
  static PART = 6
  static LEVEL = 7
  static SWING = 8
  static PRESET = 9
  static RATCHET_COUNT = 10
  static RATCHET_INTERVAL = 11
  static CHANNEL = 12
  static SKIPS = 13
  static BEAT_FRACTION = 14
  static SUBDIVISIONS = 15
  static RANDOM_DEGREE = 16
  static FADE_IN = 17
  static FADE_OUT = 18
  static SOLO = 19;
}
